### ISSUE TITLE
Description in YAML is incorrectly escaped

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipped#54]
Project links currently don't link to anything.
![link](https://cloud.githubusercontent.com/assets/5891442/5931701/01e13c44-a656-11e4-8e46-f457ead11bf8.png)

**Comment by MaxWofford** [comment]
The cause of this is that submitted descriptions with `,` and `'` symbols are not correctly escaped:
```yml
name: caster.link
description: Web-based live streaming for mobile devices. Compatible with Chrome and Firefox. Site/streaming may be down, we're trying to get our server fixed.
url: http://caster.link
github_url: https://github.com/jawerty/caster.link
authors:
  - Bogdan Vitoc
  - Jared Wright
  - Evan Klein
```
